/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.xminds.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.xminds.jira.rest.client.model.ChangedWorklog;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * List of changed worklogs.
 */
@Schema(description = "List of changed worklogs.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-10T13:09:14.296+05:30[Asia/Kolkata]")
public class ChangedWorklogs {
  @JsonProperty("values")
  private List<ChangedWorklog> values = null;

  @JsonProperty("since")
  private Long since = null;

  @JsonProperty("until")
  private Long until = null;

  @JsonProperty("self")
  private String self = null;

  @JsonProperty("nextPage")
  private String nextPage = null;

  @JsonProperty("lastPage")
  private Boolean lastPage = null;

   /**
   * Changed worklog list.
   * @return values
  **/
  @Schema(description = "Changed worklog list.")
  public List<ChangedWorklog> getValues() {
    return values;
  }

   /**
   * The datetime of the first worklog item in the list.
   * @return since
  **/
  @Schema(description = "The datetime of the first worklog item in the list.")
  public Long getSince() {
    return since;
  }

   /**
   * The datetime of the last worklog item in the list.
   * @return until
  **/
  @Schema(description = "The datetime of the last worklog item in the list.")
  public Long getUntil() {
    return until;
  }

   /**
   * The URL of this changed worklogs list.
   * @return self
  **/
  @Schema(description = "The URL of this changed worklogs list.")
  public String getSelf() {
    return self;
  }

   /**
   * The URL of the next list of changed worklogs.
   * @return nextPage
  **/
  @Schema(description = "The URL of the next list of changed worklogs.")
  public String getNextPage() {
    return nextPage;
  }

  public ChangedWorklogs lastPage(Boolean lastPage) {
    this.lastPage = lastPage;
    return this;
  }

   /**
   * Get lastPage
   * @return lastPage
  **/
  @Schema(description = "")
  public Boolean isLastPage() {
    return lastPage;
  }

  public void setLastPage(Boolean lastPage) {
    this.lastPage = lastPage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangedWorklogs changedWorklogs = (ChangedWorklogs) o;
    return Objects.equals(this.values, changedWorklogs.values) &&
        Objects.equals(this.since, changedWorklogs.since) &&
        Objects.equals(this.until, changedWorklogs.until) &&
        Objects.equals(this.self, changedWorklogs.self) &&
        Objects.equals(this.nextPage, changedWorklogs.nextPage) &&
        Objects.equals(this.lastPage, changedWorklogs.lastPage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(values, since, until, self, nextPage, lastPage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangedWorklogs {\n");
    
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    since: ").append(toIndentedString(since)).append("\n");
    sb.append("    until: ").append(toIndentedString(until)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    nextPage: ").append(toIndentedString(nextPage)).append("\n");
    sb.append("    lastPage: ").append(toIndentedString(lastPage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
