/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.xminds.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.xminds.jira.rest.client.model.RuleConfiguration;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * A workflow transition rule.
 */
@Schema(description = "A workflow transition rule.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-10T13:09:14.296+05:30[Asia/Kolkata]")
public class ConnectWorkflowTransitionRule {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("key")
  private String key = null;

  @JsonProperty("configuration")
  private RuleConfiguration _configuration = null;

  @JsonProperty("transition")
  private AllOfConnectWorkflowTransitionRuleTransition transition = null;

  public ConnectWorkflowTransitionRule id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The ID of the transition rule.
   * @return id
  **/
  @Schema(required = true, description = "The ID of the transition rule.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

   /**
   * The key of the rule, as defined in the Connect app descriptor.
   * @return key
  **/
  @Schema(required = true, description = "The key of the rule, as defined in the Connect app descriptor.")
  public String getKey() {
    return key;
  }

  public ConnectWorkflowTransitionRule _configuration(RuleConfiguration _configuration) {
    this._configuration = _configuration;
    return this;
  }

   /**
   * Get _configuration
   * @return _configuration
  **/
  @Schema(required = true, description = "")
  public RuleConfiguration getConfiguration() {
    return _configuration;
  }

  public void setConfiguration(RuleConfiguration _configuration) {
    this._configuration = _configuration;
  }

   /**
   * Get transition
   * @return transition
  **/
  @Schema(description = "")
  public AllOfConnectWorkflowTransitionRuleTransition getTransition() {
    return transition;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectWorkflowTransitionRule connectWorkflowTransitionRule = (ConnectWorkflowTransitionRule) o;
    return Objects.equals(this.id, connectWorkflowTransitionRule.id) &&
        Objects.equals(this.key, connectWorkflowTransitionRule.key) &&
        Objects.equals(this._configuration, connectWorkflowTransitionRule._configuration) &&
        Objects.equals(this.transition, connectWorkflowTransitionRule.transition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, key, _configuration, transition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectWorkflowTransitionRule {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    transition: ").append(toIndentedString(transition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
