/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.xminds.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * Details of a custom field option and its cascading options.
 */
@Schema(description = "Details of a custom field option and its cascading options.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-10T13:09:14.296+05:30[Asia/Kolkata]")
public class CustomFieldOptionDetails {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("value")
  private String value = null;

  @JsonProperty("cascadingOptions")
  private List<String> cascadingOptions = null;

   /**
   * The ID of the custom field option.
   * @return id
  **/
  @Schema(description = "The ID of the custom field option.")
  public Long getId() {
    return id;
  }

   /**
   * The value of the custom field option.
   * @return value
  **/
  @Schema(description = "The value of the custom field option.")
  public String getValue() {
    return value;
  }

   /**
   * The cascading options.
   * @return cascadingOptions
  **/
  @Schema(description = "The cascading options.")
  public List<String> getCascadingOptions() {
    return cascadingOptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomFieldOptionDetails customFieldOptionDetails = (CustomFieldOptionDetails) o;
    return Objects.equals(this.id, customFieldOptionDetails.id) &&
        Objects.equals(this.value, customFieldOptionDetails.value) &&
        Objects.equals(this.cascadingOptions, customFieldOptionDetails.cascadingOptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, value, cascadingOptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomFieldOptionDetails {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    cascadingOptions: ").append(toIndentedString(cascadingOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
