/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.xminds.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Details of a field configuration scheme.
 */
@Schema(description = "Details of a field configuration scheme.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-10T13:09:14.296+05:30[Asia/Kolkata]")
public class FieldConfigurationScheme {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  public FieldConfigurationScheme id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The ID of the field configuration scheme.
   * @return id
  **/
  @Schema(required = true, description = "The ID of the field configuration scheme.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public FieldConfigurationScheme name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the field configuration scheme.
   * @return name
  **/
  @Schema(required = true, description = "The name of the field configuration scheme.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FieldConfigurationScheme description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the field configuration scheme.
   * @return description
  **/
  @Schema(description = "The description of the field configuration scheme.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FieldConfigurationScheme fieldConfigurationScheme = (FieldConfigurationScheme) o;
    return Objects.equals(this.id, fieldConfigurationScheme.id) &&
        Objects.equals(this.name, fieldConfigurationScheme.name) &&
        Objects.equals(this.description, fieldConfigurationScheme.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FieldConfigurationScheme {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
