/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.xminds.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.xminds.jira.rest.client.model.JiraExpressionAnalysis;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * Details about the analysed Jira expression.
 */
@Schema(description = "Details about the analysed Jira expression.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-10T13:09:14.296+05:30[Asia/Kolkata]")
public class JiraExpressionsAnalysis {
  @JsonProperty("results")
  private List<JiraExpressionAnalysis> results = new ArrayList<JiraExpressionAnalysis>();

  public JiraExpressionsAnalysis results(List<JiraExpressionAnalysis> results) {
    this.results = results;
    return this;
  }

  public JiraExpressionsAnalysis addResultsItem(JiraExpressionAnalysis resultsItem) {
    this.results.add(resultsItem);
    return this;
  }

   /**
   * The results of Jira expressions analysis.
   * @return results
  **/
  @Schema(required = true, description = "The results of Jira expressions analysis.")
  public List<JiraExpressionAnalysis> getResults() {
    return results;
  }

  public void setResults(List<JiraExpressionAnalysis> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JiraExpressionsAnalysis jiraExpressionsAnalysis = (JiraExpressionsAnalysis) o;
    return Objects.equals(this.results, jiraExpressionsAnalysis.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JiraExpressionsAnalysis {\n");
    
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
