/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.xminds.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;
/**
 * Additional details about a project.
 */
@Schema(description = "Additional details about a project.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-10T13:09:14.296+05:30[Asia/Kolkata]")
public class ProjectInsight {
  @JsonProperty("totalIssueCount")
  private Long totalIssueCount = null;

  @JsonProperty("lastIssueUpdateTime")
  private OffsetDateTime lastIssueUpdateTime = null;

   /**
   * Total issue count.
   * @return totalIssueCount
  **/
  @Schema(description = "Total issue count.")
  public Long getTotalIssueCount() {
    return totalIssueCount;
  }

   /**
   * The last issue update time.
   * @return lastIssueUpdateTime
  **/
  @Schema(description = "The last issue update time.")
  public OffsetDateTime getLastIssueUpdateTime() {
    return lastIssueUpdateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectInsight projectInsight = (ProjectInsight) o;
    return Objects.equals(this.totalIssueCount, projectInsight.totalIssueCount) &&
        Objects.equals(this.lastIssueUpdateTime, projectInsight.lastIssueUpdateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalIssueCount, lastIssueUpdateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectInsight {\n");
    
    sb.append("    totalIssueCount: ").append(toIndentedString(totalIssueCount)).append("\n");
    sb.append("    lastIssueUpdateTime: ").append(toIndentedString(lastIssueUpdateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
