/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.xminds.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * A screen scheme.
 */
@Schema(description = "A screen scheme.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-10T13:09:14.296+05:30[Asia/Kolkata]")
public class ScreenScheme {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("screens")
  private AllOfScreenSchemeScreens screens = null;

  public ScreenScheme id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * The ID of the screen scheme.
   * @return id
  **/
  @Schema(description = "The ID of the screen scheme.")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ScreenScheme name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the screen scheme.
   * @return name
  **/
  @Schema(description = "The name of the screen scheme.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ScreenScheme description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the screen scheme.
   * @return description
  **/
  @Schema(description = "The description of the screen scheme.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ScreenScheme screens(AllOfScreenSchemeScreens screens) {
    this.screens = screens;
    return this;
  }

   /**
   * The IDs of the screens for the screen types of the screen scheme.
   * @return screens
  **/
  @Schema(description = "The IDs of the screens for the screen types of the screen scheme.")
  public AllOfScreenSchemeScreens getScreens() {
    return screens;
  }

  public void setScreens(AllOfScreenSchemeScreens screens) {
    this.screens = screens;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScreenScheme screenScheme = (ScreenScheme) o;
    return Objects.equals(this.id, screenScheme.id) &&
        Objects.equals(this.name, screenScheme.name) &&
        Objects.equals(this.description, screenScheme.description) &&
        Objects.equals(this.screens, screenScheme.screens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, screens);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScreenScheme {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    screens: ").append(toIndentedString(screens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
