/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.xminds.jira.rest.client.api;

import com.xminds.jira.rest.client.ApiException;
import com.xminds.jira.rest.client.model.ActorInputBean;
import com.xminds.jira.rest.client.model.ActorsMap;
import com.xminds.jira.rest.client.model.ProjectRole;
import com.xminds.jira.rest.client.model.ProjectRoleActorsUpdateBean;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProjectRoleActorsApi
 */
@Ignore
public class ProjectRoleActorsApiTest {

    private final ProjectRoleActorsApi api = new ProjectRoleActorsApi();

    /**
     * Add actors to project role
     *
     * Adds actors to a project role for the project.  To replace all actors for the project, use [Set actors for project role](#api-rest-api-3-project-projectIdOrKey-role-id-put).  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addActorUsersTest() throws ApiException {
        ActorsMap body = null;
        String projectIdOrKey = null;
        Long id = null;
        ProjectRole response = api.addActorUsers(body, projectIdOrKey, id);

        // TODO: test validations
    }
    /**
     * Add default actors to project role
     *
     * Adds [default actors](#api-rest-api-3-resolution-get) to a role. You may add groups or users, but you cannot add groups and users in the same request.  Changing a project role&#x27;s default actors does not affect project role members for projects already created.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addProjectRoleActorsToRoleTest() throws ApiException {
        ActorInputBean body = null;
        Long id = null;
        ProjectRole response = api.addProjectRoleActorsToRole(body, id);

        // TODO: test validations
    }
    /**
     * Delete actors from project role
     *
     * Deletes actors from a project role for the project.  To remove default actors from the project role, use [Delete default actors from project role](#api-rest-api-3-role-id-actors-delete).  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteActorTest() throws ApiException {
        String projectIdOrKey = null;
        Long id = null;
        String user = null;
        String group = null;
        api.deleteActor(projectIdOrKey, id, user, group);

        // TODO: test validations
    }
    /**
     * Delete default actors from project role
     *
     * Deletes the [default actors](#api-rest-api-3-resolution-get) from a project role. You may delete a group or user, but you cannot delete a group and a user in the same request.  Changing a project role&#x27;s default actors does not affect project role members for projects already created.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteProjectRoleActorsFromRoleTest() throws ApiException {
        Long id = null;
        String user = null;
        String group = null;
        ProjectRole response = api.deleteProjectRoleActorsFromRole(id, user, group);

        // TODO: test validations
    }
    /**
     * Get default actors for project role
     *
     * Returns the [default actors](#api-rest-api-3-resolution-get) for the project role.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProjectRoleActorsForRoleTest() throws ApiException {
        Long id = null;
        ProjectRole response = api.getProjectRoleActorsForRole(id);

        // TODO: test validations
    }
    /**
     * Set actors for project role
     *
     * Sets the actors for a project role for a project, replacing all existing actors.  To add actors to the project without overwriting the existing list, use [Add actors to project role](#api-rest-api-3-project-projectIdOrKey-role-id-post).  **[Permissions](#permissions) required:** *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setActorsTest() throws ApiException {
        ProjectRoleActorsUpdateBean body = null;
        String projectIdOrKey = null;
        Long id = null;
        ProjectRole response = api.setActors(body, projectIdOrKey, id);

        // TODO: test validations
    }
}
