/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.xminds.jira.rest.client.api;

import com.xminds.jira.rest.client.ApiException;
import com.xminds.jira.rest.client.model.ErrorCollection;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProjectKeyAndNameValidationApi
 */
@Ignore
public class ProjectKeyAndNameValidationApiTest {

    private final ProjectKeyAndNameValidationApi api = new ProjectKeyAndNameValidationApi();

    /**
     * Get valid project key
     *
     * Validates a project key and, if the key is invalid or in use, generates a valid random string for the project key.  **[Permissions](#permissions) required:** None.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getValidProjectKeyTest() throws ApiException {
        String key = null;
        String response = api.getValidProjectKey(key);

        // TODO: test validations
    }
    /**
     * Get valid project name
     *
     * Checks that a project name isn&#x27;t in use. If the name isn&#x27;t in use, the passed string is returned. If the name is in use, this operation attempts to generate a valid project name based on the one supplied, usually by adding a sequence number. If a valid project name cannot be generated, a 404 response is returned.  **[Permissions](#permissions) required:** None.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getValidProjectNameTest() throws ApiException {
        String name = null;
        String response = api.getValidProjectName(name);

        // TODO: test validations
    }
    /**
     * Validate project key
     *
     * Validates a project key by confirming the key is a valid string and not in use.  **[Permissions](#permissions) required:** None.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void validateProjectKeyTest() throws ApiException {
        String key = null;
        ErrorCollection response = api.validateProjectKey(key);

        // TODO: test validations
    }
}
