/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.xminds.jira.rest.client.api;

import com.xminds.jira.rest.client.ApiException;
import com.xminds.jira.rest.client.model.Avatar;
import com.xminds.jira.rest.client.model.ProjectAvatars;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProjectAvatarsApi
 */
@Ignore
public class ProjectAvatarsApiTest {

    private final ProjectAvatarsApi api = new ProjectAvatarsApi();

    /**
     * Load project avatar
     *
     * Loads an avatar for a project.  Specify the avatar&#x27;s local file location in the body of the request. Also, include the following headers:   *  &#x60;X-Atlassian-Token: no-check&#x60; To prevent XSRF protection blocking the request, for more information see [Special Headers](#special-request-headers).  *  &#x60;Content-Type: image/image type&#x60; Valid image types are JPEG, GIF, or PNG.  For example:   &#x60;curl --request POST &#x60;  &#x60;--user email@example.com:&lt;api_token&gt; &#x60;  &#x60;--header &#x27;X-Atlassian-Token: no-check&#x27; &#x60;  &#x60;--header &#x27;Content-Type: image/&lt; image_type&gt;&#x27; &#x60;  &#x60;--data-binary \&quot;&lt;@/path/to/file/with/your/avatar&gt;\&quot; &#x60;  &#x60;--url &#x27;https://your-domain.atlassian.net/rest/api/3/project/{projectIdOrKey}/avatar2&#x27;&#x60;  The avatar is cropped to a square. If no crop parameters are specified, the square originates at the top left of the image. The length of the square&#x27;s sides is set to the smaller of the height or width of the image.  The cropped image is then used to create avatars of 16x16, 24x24, 32x32, and 48x48 in size.  After creating the avatar use [Set project avatar](#api-rest-api-3-project-projectIdOrKey-avatar-put) to set it as the project&#x27;s displayed avatar.  **[Permissions](#permissions) required:** *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createProjectAvatarTest() throws ApiException {
        Object body = null;
        String projectIdOrKey = null;
        Integer x = null;
        Integer y = null;
        Integer size = null;
        Avatar response = api.createProjectAvatar(body, projectIdOrKey, x, y, size);

        // TODO: test validations
    }
    /**
     * Delete project avatar
     *
     * Deletes a custom avatar from a project. Note that system avatars cannot be deleted.  **[Permissions](#permissions) required:** *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteProjectAvatarTest() throws ApiException {
        String projectIdOrKey = null;
        Long id = null;
        api.deleteProjectAvatar(projectIdOrKey, id);

        // TODO: test validations
    }
    /**
     * Get all project avatars
     *
     * Returns all project avatars, grouped by system and custom avatars.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllProjectAvatarsTest() throws ApiException {
        String projectIdOrKey = null;
        ProjectAvatars response = api.getAllProjectAvatars(projectIdOrKey);

        // TODO: test validations
    }
    /**
     * Set project avatar
     *
     * Sets the avatar displayed for a project.  Use [Load project avatar](#api-rest-api-3-project-projectIdOrKey-avatar2-post) to store avatars against the project, before using this operation to set the displayed avatar.  **[Permissions](#permissions) required:** *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateProjectAvatarTest() throws ApiException {
        Avatar body = null;
        String projectIdOrKey = null;
        Object response = api.updateProjectAvatar(body, projectIdOrKey);

        // TODO: test validations
    }
}
